version: '2'
services:
#-----------------------------------------------------------------
  elasticsearch:
    build:
      context: elasticsearch/
    container_name: 'elasticsearch'
    restart: 'always'
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
#-----------------------------------------------------------------
  scripts:
    build:
      context: scripts/
    container_name: 'scripts'
    restart: 'always'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elk
#-----------------------------------------------------------------
  grafana:
    image: grafana/grafana:5.1.0
    container_name: 'Grafana'
    restart: always
    ports:
      - "3000:3000"
    networks:
      - elk
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./data/:/var/lib/grafana/plugins/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_GRAFANA_PLUGIN_LIST="grafana-clock-panel,jdbranham-diagram-panel,camptocamp-prometheus-alertmanager-datasource"
     # - GF_SMTP_ENABLED=true
     # - GF_SMTP_HOST=smtp.gmail.com:587
     # - GF_SMTP_USER=grafana@example.com
     # - GF_SMTP_FROM_ADDRESS=grafana@example.com
     # - GF_SMTP_PASSWORD=mailpass
     # - GF_USERS_ALLOW_SIGN_UP=false
#-----------------------------------------------------------------
networks:
  elk:
    driver: bridge
