version: '2'
services:
#-----------------------------------------------------------------
  nginx:
    image: nginx
    ports:
      - 9200:9200
      - 5601:5601
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/htpasswd:/etc/nginx/nginx.conf
    networks:
      - elk
#-----------------------------------------------------------------
  elasticsearch:
    build:
      context: elasticsearch/
    container_name: 'elasticsearch'
    restart: 'always'
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9209:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - nginx
#-----------------------------------------------------------------
  kibana:
    build:
      context: kibana/
    container_name: 'kibana'
    restart: 'always'
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5609:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - nginx
#-----------------------------------------------------------------
networks:
  elk:
    driver: bridge
