{
 "title": "Openstack",
 "time": { "from": "2018-06-15T20:49:03.477Z", "to": "2018-06-15T20:50:33.925Z" },
 "panels": [
  {
   "title": "RUNNING INSTANCES",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "openstack_running_instances" }
   ]
  },
  {
   "title": "SERVICE NOVA COMPUTE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_services_nova_nova_compute"
    }
   ]
  },
  {
   "title": "SERVICE NOVA COMPUTE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_services_nova_nova_compute"
    }
   ]
  },
  {
   "title": "SERVICE NOVA CONSOLEAUTH",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_services_nova_nova_consoleauth"
    }
   ]
  },
  {
   "title": "free_disk_GB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    { "expr": "openstack_free_disk_GB" }
   ]
  },
  {
   "title": "free_disk_GB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    { "expr": "openstack_free_disk_GB" }
   ]
  },
  {
   "title": "NEUTRON API",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "openstack_check_neutron_api" }
   ]
  },
  {
   "title": "NOVA API",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "openstack_check_nova_api" }
   ]
  },
  {
   "title": "NOVA API",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "openstack_check_nova_api" }
   ]
  },
  {
   "title": "total_used_vcpus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "openstack_total_used_vcpus" }
   ]
  },
  {
   "title": "RAM USED (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "openstack_used_ram_MB" }
   ]
  }
 ]
}